uploads = []

[[generated]]
id = "pLufypxm1aAY9jLpSQSQE"
uri = "file://artifacts/pulse-pilot/assets/images/icon.png"
type = "image"
title = "Viva Icon"

[[outputs]]
id = "sr2iti8pEAHPDQXBl-NFR"
uri = "file://viva-project.tar.gz"
type = "unspecified"
title = "VIVA Project (tar.gz)"
