/**
 * Curated intervention library — 30 rule-based, pilot-safe entries.
 *
 * Design rules:
 *  - Each step is completable in 10–30 minutes
 *  - Copy uses "try", "may help", "can support" — never guarantees
 *  - No medication advice, no diagnosis, no lifestyle coaching
 *  - avoidIfSevereNausea / avoidIfLowAppetite filter unsafe entries automatically
 *  - strategyType drives cross-strategy rotation in the adjusted support step
 */

import type { LibraryEntry } from "./types";

export const LIBRARY: LibraryEntry[] = [
  // ── NAUSEA ─────────────────────────────────────────────────────────

  {
    id: "nausea-sip-electrolyte-slow",
    strategyType: "hydration-first",
    symptomTargets: ["nausea", "hydration"],
    severityTiers: ["mild", "moderate"],
    behavioralBurden: "low",
    expectedFeedbackWindowMinutes: 20,
    hydrationRelated: true,
    foodRelated: false,
    movementRelated: false,
    nervousSystemRelated: false,
    recoveryFocused: false,
    postDoseRelevant: true,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: false,
    escalationPrevention: false,
    exampleContextTriggers: ["nausea mild", "nausea moderate", "low hydration"],
    copy: {
      title: "Sip slowly for 20 minutes",
      body: "Take 4–5 slow sips of water, Pedialyte, or an electrolyte drink right now. Repeat every 5 minutes for the next 20 minutes. No solid food yet.",
      helper: "Steady sips absorb better than gulping and are easier to keep down when nausea is active.",
    },
  },

  {
    id: "nausea-ginger-tea-upright",
    strategyType: "warm-fluid-digestion",
    symptomTargets: ["nausea"],
    severityTiers: ["mild", "moderate"],
    behavioralBurden: "low",
    expectedFeedbackWindowMinutes: 15,
    hydrationRelated: true,
    foodRelated: false,
    movementRelated: false,
    nervousSystemRelated: false,
    recoveryFocused: false,
    postDoseRelevant: true,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: false,
    escalationPrevention: false,
    exampleContextTriggers: ["nausea mild", "nausea moderate", "post-dose window"],
    copy: {
      title: "Warm ginger or peppermint tea, upright",
      body: "Brew or buy a cup of warm ginger tea or peppermint tea. Sip it slowly over 10–15 minutes while sitting fully upright. Avoid lying down.",
      helper: "Warm fluids may calm stomach contractions; staying upright can reduce pressure that worsens nausea.",
    },
  },

  {
    id: "nausea-pause-cold-fluids",
    strategyType: "hydration-first",
    symptomTargets: ["nausea"],
    severityTiers: ["moderate", "severe"],
    behavioralBurden: "low",
    expectedFeedbackWindowMinutes: 20,
    hydrationRelated: true,
    foodRelated: false,
    movementRelated: false,
    nervousSystemRelated: false,
    recoveryFocused: false,
    postDoseRelevant: true,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: false,
    escalationPrevention: true,
    exampleContextTriggers: ["nausea moderate", "nausea severe", "can't keep food down"],
    copy: {
      title: "Pause food: small sips every 2 minutes",
      body: "Stop solid food for now. Try ice chips or a chilled electrolyte drink like Pedialyte. Take a few sips every 2 minutes for the next 15 minutes. If nausea eases, try 2–3 plain crackers.",
      helper: "If nausea worsens or you can't keep fluids down, contact your care team.",
    },
  },

  {
    id: "nausea-fresh-air-upright",
    strategyType: "posture-upright-reset",
    symptomTargets: ["nausea"],
    severityTiers: ["mild", "moderate"],
    behavioralBurden: "low",
    expectedFeedbackWindowMinutes: 10,
    hydrationRelated: false,
    foodRelated: false,
    movementRelated: false,
    nervousSystemRelated: true,
    recoveryFocused: false,
    postDoseRelevant: false,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: false,
    escalationPrevention: false,
    exampleContextTriggers: ["nausea mild", "nausea moderate", "indoor/stuffy environment"],
    copy: {
      title: "Fresh air and upright posture for 5 minutes",
      body: "Step outside or open a window. Sit upright and breathe slowly: in through the nose for 4 counts, out through the mouth for 6. Repeat for 5 minutes. Then take 4–5 sips of cold water.",
      helper: "Fresh air and upright breathing can ease nausea quickly before you try any food or drink.",
    },
  },

  {
    id: "nausea-low-stimulation-quiet-room",
    strategyType: "low-stimulation-reset",
    symptomTargets: ["nausea"],
    severityTiers: ["moderate", "severe"],
    behavioralBurden: "low",
    expectedFeedbackWindowMinutes: 20,
    hydrationRelated: false,
    foodRelated: false,
    movementRelated: false,
    nervousSystemRelated: true,
    recoveryFocused: false,
    postDoseRelevant: true,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: false,
    escalationPrevention: true,
    exampleContextTriggers: ["nausea severe", "nausea moderate", "high activity day", "post-dose"],
    copy: {
      title: "Quiet, cool room for 15 minutes",
      body: "Move to a quiet, cool spot. Avoid screens, strong smells, and food for 15 minutes. Sip small amounts of water every 3 minutes. Then reassess.",
      helper: "Reducing sensory input can lower nausea intensity without needing medication.",
    },
  },

  {
    id: "nausea-crackers-toast",
    strategyType: "food-first",
    symptomTargets: ["nausea", "appetite"],
    severityTiers: ["mild"],
    behavioralBurden: "low",
    expectedFeedbackWindowMinutes: 15,
    hydrationRelated: false,
    foodRelated: true,
    movementRelated: false,
    nervousSystemRelated: false,
    recoveryFocused: false,
    postDoseRelevant: false,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: true,
    escalationPrevention: false,
    exampleContextTriggers: ["nausea mild", "empty stomach"],
    copy: {
      title: "2–3 plain crackers or a slice of toast",
      body: "Try 2–3 plain crackers or a slice of dry toast now. Eat very slowly. Stop immediately if nausea increases. Don't push through it.",
      helper: "A small amount of bland starch can settle mild nausea better than an empty stomach.",
    },
  },

  // ── APPETITE ───────────────────────────────────────────────────────

  {
    id: "appetite-small-protein-bites",
    strategyType: "food-first",
    symptomTargets: ["appetite"],
    severityTiers: ["mild", "moderate"],
    behavioralBurden: "low",
    expectedFeedbackWindowMinutes: 15,
    hydrationRelated: false,
    foodRelated: true,
    movementRelated: false,
    nervousSystemRelated: false,
    recoveryFocused: false,
    postDoseRelevant: false,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: true,
    escalationPrevention: false,
    exampleContextTriggers: ["low appetite", "low food intake"],
    copy: {
      title: "2–3 bites of protein, then pause",
      body: "Eat 2–3 bites of Greek yogurt, soft tofu, a hard-boiled egg, or cottage cheese right now. Stop there. Wait 10 minutes, then check how your stomach feels before eating more.",
      helper: "Micro-portions of protein keep nutrition coming in without overwhelming a low appetite.",
    },
  },

  {
    id: "appetite-protein-smoothie",
    strategyType: "food-first",
    symptomTargets: ["appetite"],
    severityTiers: ["mild"],
    behavioralBurden: "medium",
    expectedFeedbackWindowMinutes: 20,
    hydrationRelated: true,
    foodRelated: true,
    movementRelated: false,
    nervousSystemRelated: false,
    recoveryFocused: false,
    postDoseRelevant: false,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: true,
    escalationPrevention: false,
    exampleContextTriggers: ["low appetite", "low energy", "mild nausea with low food intake"],
    copy: {
      title: "Sip a small protein smoothie",
      body: "Blend or buy a small smoothie with Greek yogurt, cottage cheese, or protein powder. Sip 4–6 oz slowly over 10–15 minutes. No rush.",
      helper: "Liquid protein may be easier to take in when chewing or strong flavors feel like too much.",
    },
  },

  {
    id: "appetite-warm-broth-first",
    strategyType: "hydration-first",
    symptomTargets: ["appetite", "hydration"],
    severityTiers: ["mild", "moderate"],
    behavioralBurden: "low",
    expectedFeedbackWindowMinutes: 15,
    hydrationRelated: true,
    foodRelated: false,
    movementRelated: false,
    nervousSystemRelated: false,
    recoveryFocused: false,
    postDoseRelevant: true,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: false,
    escalationPrevention: false,
    exampleContextTriggers: ["very low appetite", "low food intake", "nausea with appetite loss"],
    copy: {
      title: "Warm broth before solid food",
      body: "Sip 4–6 oz of warm chicken or vegetable broth now. Wait 10 minutes. If it settled well, try 2–3 small bites of a familiar food.",
      helper: "Broth provides fluid and trace nutrition without the texture or volume that can feel overwhelming on a low-appetite day.",
    },
  },

  {
    id: "appetite-timed-bites",
    strategyType: "food-first",
    symptomTargets: ["appetite"],
    severityTiers: ["mild", "moderate"],
    behavioralBurden: "medium",
    expectedFeedbackWindowMinutes: 20,
    hydrationRelated: false,
    foodRelated: true,
    movementRelated: false,
    nervousSystemRelated: false,
    recoveryFocused: false,
    postDoseRelevant: false,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: true,
    escalationPrevention: false,
    exampleContextTriggers: ["low appetite", "skipping meals"],
    copy: {
      title: "One bite every 5 minutes",
      body: "Set a 20-minute timer. Every 5 minutes, eat one small bite of a familiar food: yogurt, banana, crackers, or soup. Stop when the timer finishes.",
      helper: "Ultra-slow pacing takes pressure off the stomach and often leads to more total intake than forcing a full meal.",
    },
  },

  // ── LOW ENERGY ─────────────────────────────────────────────────────

  {
    id: "energy-walk-3min",
    strategyType: "gentle-movement",
    symptomTargets: ["energy"],
    severityTiers: ["mild", "moderate"],
    behavioralBurden: "low",
    expectedFeedbackWindowMinutes: 10,
    hydrationRelated: false,
    foodRelated: false,
    movementRelated: true,
    nervousSystemRelated: false,
    recoveryFocused: false,
    postDoseRelevant: false,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: true,
    escalationPrevention: false,
    exampleContextTriggers: ["tired energy", "low steps", "mild fatigue"],
    copy: {
      title: "A slow 3-minute walk",
      body: "Take a slow, easy 3-minute walk around the room or outside. No pace target. Just move gently. Drink 6–8 oz of water before or after.",
      helper: "Even a very short walk after fluids may shift tired energy more than rest does.",
    },
  },

  {
    id: "energy-sunlight-window",
    strategyType: "gentle-movement",
    symptomTargets: ["energy"],
    severityTiers: ["mild"],
    behavioralBurden: "low",
    expectedFeedbackWindowMinutes: 10,
    hydrationRelated: false,
    foodRelated: false,
    movementRelated: false,
    nervousSystemRelated: true,
    recoveryFocused: false,
    postDoseRelevant: false,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: false,
    escalationPrevention: false,
    exampleContextTriggers: ["mild fatigue", "low activity", "daytime fatigue"],
    copy: {
      title: "5 minutes near bright light",
      body: "Step outside or sit near a bright window for 5 minutes. Sit upright and try not to look at a screen. Then drink 6–8 oz of water.",
      helper: "Natural or bright light may help reset alertness without physical effort.",
    },
  },

  {
    id: "energy-rest-15min",
    strategyType: "rest-recovery-reset",
    symptomTargets: ["energy"],
    severityTiers: ["moderate", "severe"],
    behavioralBurden: "low",
    expectedFeedbackWindowMinutes: 20,
    hydrationRelated: false,
    foodRelated: false,
    movementRelated: false,
    nervousSystemRelated: false,
    recoveryFocused: true,
    postDoseRelevant: true,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: false,
    escalationPrevention: false,
    exampleContextTriggers: ["depleted energy", "severe fatigue", "low HRV", "poor sleep"],
    copy: {
      title: "15-minute intentional rest",
      body: "Find a quiet spot. Lie down or sit comfortably with no phone or screen. Set a timer for 15 minutes. Breathe slowly. Reassess how you feel after.",
      helper: "A short intentional rest may restore more energy than pushing through on low reserves.",
    },
  },

  {
    id: "energy-hydration-first",
    strategyType: "hydration-first",
    symptomTargets: ["energy", "hydration"],
    severityTiers: ["mild", "moderate"],
    behavioralBurden: "low",
    expectedFeedbackWindowMinutes: 15,
    hydrationRelated: true,
    foodRelated: false,
    movementRelated: false,
    nervousSystemRelated: false,
    recoveryFocused: false,
    postDoseRelevant: true,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: false,
    escalationPrevention: false,
    exampleContextTriggers: ["tired energy", "low hydration", "high activity day"],
    copy: {
      title: "Drink 8 oz of water or electrolytes now",
      body: "Drink a full 8 oz of water or an electrolyte drink (Pedialyte, LMNT, or water with a pinch of salt) right now. Sit quietly for 5 minutes after.",
      helper: "Even mild dehydration can intensify fatigue, which is common on GLP-1 medications when appetite and fluid intake are lower than usual.",
    },
  },

  {
    id: "energy-protein-carb-refuel",
    strategyType: "food-first",
    symptomTargets: ["energy", "appetite"],
    severityTiers: ["mild"],
    behavioralBurden: "medium",
    expectedFeedbackWindowMinutes: 20,
    hydrationRelated: false,
    foodRelated: true,
    movementRelated: false,
    nervousSystemRelated: false,
    recoveryFocused: false,
    postDoseRelevant: false,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: true,
    escalationPrevention: false,
    exampleContextTriggers: ["tired energy", "low food intake", "skipped meal"],
    copy: {
      title: "Small protein-and-carb combination",
      body: "Eat a small protein-and-carb combo now: Greek yogurt with a banana, eggs on toast, or soup with soft tofu. Rest for 10 minutes after eating.",
      helper: "Protein paired with a carb may stabilize energy more reliably than either one alone.",
    },
  },

  // ── DIGESTION / CONSTIPATION ────────────────────────────────────────

  {
    id: "digestion-warm-water-walk",
    strategyType: "warm-fluid-digestion",
    symptomTargets: ["digestion"],
    severityTiers: ["mild", "moderate"],
    behavioralBurden: "medium",
    expectedFeedbackWindowMinutes: 20,
    hydrationRelated: true,
    foodRelated: false,
    movementRelated: true,
    nervousSystemRelated: false,
    recoveryFocused: false,
    postDoseRelevant: false,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: false,
    escalationPrevention: false,
    exampleContextTriggers: ["constipation", "no bowel movement", "digestion discomfort"],
    copy: {
      title: "Warm water, then a 5-minute walk",
      body: "Drink a full glass of warm water right now. Then take a slow 5-minute walk around the room or outside. Stay upright for 20 minutes total.",
      helper: "Warm fluids can relax the gut; gentle movement may stimulate digestion in a way rest cannot.",
    },
  },

  {
    id: "digestion-abdominal-breathing",
    strategyType: "low-stimulation-reset",
    symptomTargets: ["digestion"],
    severityTiers: ["mild"],
    behavioralBurden: "low",
    expectedFeedbackWindowMinutes: 15,
    hydrationRelated: false,
    foodRelated: false,
    movementRelated: false,
    nervousSystemRelated: true,
    recoveryFocused: false,
    postDoseRelevant: false,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: false,
    escalationPrevention: false,
    exampleContextTriggers: ["constipation mild", "bloating", "digestion discomfort"],
    copy: {
      title: "5 slow belly breaths",
      body: "Sit upright in a chair. Breathe in slowly through your nose for 4 counts, letting your belly expand. Breathe out through your mouth for 6 counts. Repeat 5 times, then take a slow 5-minute walk.",
      helper: "Deep belly breathing activates the parasympathetic system, which may stimulate bowel movement.",
    },
  },

  {
    id: "digestion-upright-posture",
    strategyType: "posture-upright-reset",
    symptomTargets: ["digestion"],
    severityTiers: ["mild", "moderate"],
    behavioralBurden: "low",
    expectedFeedbackWindowMinutes: 20,
    hydrationRelated: false,
    foodRelated: false,
    movementRelated: false,
    nervousSystemRelated: false,
    recoveryFocused: false,
    postDoseRelevant: true,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: false,
    escalationPrevention: false,
    exampleContextTriggers: ["digestion discomfort", "after eating", "bloating"],
    copy: {
      title: "Sit fully upright for 15 minutes",
      body: "Sit up straight in a chair, not reclined and not lying down. Drink 6–8 oz of water. Stay upright for at least 15 minutes, then reassess discomfort.",
      helper: "Gravity supports digestion when you stay upright after a meal or fluids.",
    },
  },

  {
    id: "digestion-warm-prune-juice",
    strategyType: "warm-fluid-digestion",
    symptomTargets: ["digestion"],
    severityTiers: ["moderate"],
    behavioralBurden: "low",
    expectedFeedbackWindowMinutes: 30,
    hydrationRelated: true,
    foodRelated: false,
    movementRelated: false,
    nervousSystemRelated: false,
    recoveryFocused: false,
    postDoseRelevant: false,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: false,
    escalationPrevention: false,
    exampleContextTriggers: ["constipation moderate", "no bowel movement 2+ days"],
    copy: {
      title: "4 oz of warm prune or apple juice",
      body: "Warm 4 oz of prune juice or apple juice (not cold). Sip it slowly. Stay upright for 20–30 minutes after. Follow with 8 oz of plain water.",
      helper: "Warm prune or apple juice can support bowel movement gently without a harsh laxative effect.",
    },
  },

  {
    id: "digestion-gentle-walk",
    strategyType: "gentle-movement",
    symptomTargets: ["digestion"],
    severityTiers: ["mild", "moderate"],
    behavioralBurden: "low",
    expectedFeedbackWindowMinutes: 15,
    hydrationRelated: false,
    foodRelated: false,
    movementRelated: true,
    nervousSystemRelated: false,
    recoveryFocused: false,
    postDoseRelevant: false,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: false,
    escalationPrevention: false,
    exampleContextTriggers: ["constipation", "sluggish digestion", "sedentary day"],
    copy: {
      title: "A slow 5-minute walk now",
      body: "Stand up and take a slow, relaxed 5-minute walk outside or around the room. Drink 8 oz of water before or right after.",
      helper: "Gentle movement is one of the most reliable short-term supports for a sluggish digestive system.",
    },
  },

  // ── SLEEP DISRUPTION ────────────────────────────────────────────────

  {
    id: "sleep-wind-down-screen",
    strategyType: "sleep-downshift",
    symptomTargets: ["sleep"],
    severityTiers: ["mild"],
    behavioralBurden: "low",
    expectedFeedbackWindowMinutes: 30,
    hydrationRelated: false,
    foodRelated: false,
    movementRelated: false,
    nervousSystemRelated: true,
    recoveryFocused: true,
    postDoseRelevant: false,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: false,
    escalationPrevention: false,
    exampleContextTriggers: ["poor sleep", "sleep disruption", "pre-bedtime"],
    copy: {
      title: "Dim screens and skip food for 60 minutes",
      body: "Switch your phone or tablet to night mode or dim it fully. If bedtime is within 2 hours, avoid eating for the next 60 minutes. Drink 4–6 oz of water at room temperature.",
      helper: "Screen dimming and a pre-sleep hydration routine may support a smoother wind-down.",
    },
  },

  {
    id: "sleep-breathwork-4-7-8",
    strategyType: "low-stimulation-reset",
    symptomTargets: ["sleep", "energy"],
    severityTiers: ["mild", "moderate"],
    behavioralBurden: "low",
    expectedFeedbackWindowMinutes: 15,
    hydrationRelated: false,
    foodRelated: false,
    movementRelated: false,
    nervousSystemRelated: true,
    recoveryFocused: true,
    postDoseRelevant: false,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: false,
    escalationPrevention: false,
    exampleContextTriggers: ["poor sleep", "restless", "anxiety", "pre-bedtime"],
    copy: {
      title: "4-7-8 breathing, 4 rounds",
      body: "Sit or lie comfortably. Inhale through your nose for 4 seconds. Hold for 7 seconds. Exhale through your mouth for 8 seconds. Repeat 4 times.",
      helper: "This breathing pattern activates the parasympathetic nervous system and may support a faster transition to sleep.",
    },
  },

  {
    id: "sleep-cool-room",
    strategyType: "sleep-downshift",
    symptomTargets: ["sleep"],
    severityTiers: ["mild"],
    behavioralBurden: "low",
    expectedFeedbackWindowMinutes: 30,
    hydrationRelated: false,
    foodRelated: false,
    movementRelated: false,
    nervousSystemRelated: false,
    recoveryFocused: true,
    postDoseRelevant: false,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: false,
    escalationPrevention: false,
    exampleContextTriggers: ["sleep disruption", "warm room", "poor sleep quality"],
    copy: {
      title: "Lower room temperature slightly",
      body: "Open a window, turn on a fan, or lower the thermostat slightly if possible. Remove one heavy blanket. A cooler room (around 65–68°F) may support deeper sleep.",
      helper: "Core body temperature naturally drops during sleep; a cooler room may help that transition.",
    },
  },

  {
    id: "sleep-hydration-bedtime",
    strategyType: "hydration-first",
    symptomTargets: ["sleep", "hydration"],
    severityTiers: ["mild"],
    behavioralBurden: "low",
    expectedFeedbackWindowMinutes: 30,
    hydrationRelated: true,
    foodRelated: false,
    movementRelated: false,
    nervousSystemRelated: false,
    recoveryFocused: true,
    postDoseRelevant: false,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: false,
    escalationPrevention: false,
    exampleContextTriggers: ["poor sleep", "low hydration", "waking at night"],
    copy: {
      title: "4–6 oz of water 30 minutes before bed",
      body: "Sip 4–6 oz of water at room temperature about 30 minutes before you plan to sleep. Not cold, not a full glass. Just enough to stay hydrated overnight.",
      helper: "Staying hydrated overnight may reduce mid-night waking caused by thirst or dry mouth.",
    },
  },

  // ── HYDRATION ───────────────────────────────────────────────────────

  {
    id: "hydration-timed-sip-protocol",
    strategyType: "hydration-first",
    symptomTargets: ["hydration", "nausea"],
    severityTiers: ["mild", "moderate", "severe"],
    behavioralBurden: "low",
    expectedFeedbackWindowMinutes: 30,
    hydrationRelated: true,
    foodRelated: false,
    movementRelated: false,
    nervousSystemRelated: false,
    recoveryFocused: false,
    postDoseRelevant: true,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: false,
    escalationPrevention: true,
    exampleContextTriggers: ["dehydration", "low fluid intake", "diarrhea", "nausea"],
    copy: {
      title: "4–5 sips every 5 minutes for 30 minutes",
      body: "Take 4–5 sips of water or an electrolyte drink (Pedialyte, LMNT, or water with a pinch of salt) right now. Repeat every 5 minutes for the next 30 minutes.",
      helper: "Steady timed sips absorb more efficiently and are easier to keep down than drinking a large amount at once.",
    },
  },

  {
    id: "hydration-electrolyte-switch",
    strategyType: "hydration-first",
    symptomTargets: ["hydration"],
    severityTiers: ["mild", "moderate"],
    behavioralBurden: "low",
    expectedFeedbackWindowMinutes: 20,
    hydrationRelated: true,
    foodRelated: false,
    movementRelated: false,
    nervousSystemRelated: false,
    recoveryFocused: false,
    postDoseRelevant: false,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: false,
    escalationPrevention: false,
    exampleContextTriggers: ["low hydration", "plain water not working", "nausea with dehydration"],
    copy: {
      title: "Switch to an electrolyte drink",
      body: "Try Pedialyte, LMNT, Liquid I.V., or water with a pinch of salt and a squeeze of lemon. Take small sips every 5 minutes for the next 20 minutes.",
      helper: "Electrolytes provide more efficient rehydration than plain water and are often easier to tolerate when nausea is present.",
    },
  },

  {
    id: "hydration-warm-fluids",
    strategyType: "warm-fluid-digestion",
    symptomTargets: ["hydration", "digestion"],
    severityTiers: ["mild", "moderate"],
    behavioralBurden: "low",
    expectedFeedbackWindowMinutes: 20,
    hydrationRelated: true,
    foodRelated: false,
    movementRelated: false,
    nervousSystemRelated: false,
    recoveryFocused: false,
    postDoseRelevant: false,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: false,
    escalationPrevention: false,
    exampleContextTriggers: ["low hydration", "cold drinks not tolerated", "digestion discomfort"],
    copy: {
      title: "Warm water or herbal tea, small sips",
      body: "Try warm water, ginger tea, or peppermint tea. Take a few small sips every 3–5 minutes for the next 20 minutes. Don't force it down.",
      helper: "A temperature change often makes fluids easier to tolerate when cold water feels off or worsens nausea.",
    },
  },

  // ── GENERAL / OTHER ─────────────────────────────────────────────────

  {
    id: "general-one-action-now",
    strategyType: "low-stimulation-reset",
    symptomTargets: ["nausea", "appetite", "energy"],
    severityTiers: ["mild", "moderate"],
    behavioralBurden: "low",
    expectedFeedbackWindowMinutes: 10,
    hydrationRelated: false,
    foodRelated: false,
    movementRelated: false,
    nervousSystemRelated: false,
    recoveryFocused: false,
    postDoseRelevant: false,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: false,
    escalationPrevention: false,
    exampleContextTriggers: ["multiple symptoms", "overwhelmed", "uncertain where to start"],
    copy: {
      title: "Sit upright and breathe slowly for 5 minutes",
      body: "Sit upright in a quiet spot. Breathe in through your nose for 4 counts, out through your mouth for 6. Repeat for 5 minutes. Then take 4–5 slow sips of water.",
      helper: "A short quiet reset can help when multiple symptoms are competing for attention.",
    },
  },

  {
    id: "general-posture-reset",
    strategyType: "posture-upright-reset",
    symptomTargets: ["nausea", "digestion", "energy"],
    severityTiers: ["mild", "moderate"],
    behavioralBurden: "low",
    expectedFeedbackWindowMinutes: 10,
    hydrationRelated: false,
    foodRelated: false,
    movementRelated: false,
    nervousSystemRelated: false,
    recoveryFocused: false,
    postDoseRelevant: true,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: false,
    escalationPrevention: false,
    exampleContextTriggers: ["after meal", "nausea", "digestion", "post-dose"],
    copy: {
      title: "Sit upright for 10 minutes",
      body: "Sit fully upright in a chair, not reclined and not lying down. Take 4–5 slow sips of water. Stay in this position for 10 minutes.",
      helper: "Upright posture can reduce pressure on the stomach and may ease both nausea and digestion discomfort.",
    },
  },

  {
    id: "general-quiet-rest",
    strategyType: "rest-recovery-reset",
    symptomTargets: ["nausea", "energy", "sleep"],
    severityTiers: ["moderate", "severe"],
    behavioralBurden: "low",
    expectedFeedbackWindowMinutes: 20,
    hydrationRelated: false,
    foodRelated: false,
    movementRelated: false,
    nervousSystemRelated: false,
    recoveryFocused: true,
    postDoseRelevant: true,
    avoidIfLowAppetite: false,
    avoidIfSevereNausea: false,
    escalationPrevention: true,
    exampleContextTriggers: ["severe symptoms", "multiple moderate symptoms", "high symptom burden"],
    copy: {
      title: "10 minutes of quiet rest",
      body: "Find a quiet spot. Sit or lie down for 10 minutes with no phone or screen. Focus on slow breathing: in for 4, out for 6. Reassess how you feel after.",
      helper: "When symptoms feel like too much, a short rest without stimulation is often the best first step before trying anything else.",
    },
  },
];
